contextPath: /acl
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/acls?useUnicode=yes&characterEncoding=UTF-8}
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.jdbc.Driver}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
server:
  port: ${SERVER_PORT:8002}
flyway:
  locations: classpath:/db/migration
logging:
  level:
    org:
      springframework: INFO
---
spring:
  profiles: dev
---
spring:
  profiles: test
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS:org.h2.Driver}
    url: ${DB_URL:jdbc:h2:mem:acls;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:/h2/migration/init_tests.sql'}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
flyway:
  locations: classpath:/db/migration,classpath:/h2/migration